### ISSUE TITLE
Iterative Hessian Sketch

### ISSUE THREAD

**Issue by VChristian** [numlinalg/RLinearAlgebra.jl#52]
Implement Iterative Hessian Sketch Method.

1. Implementation
- [x] Create a file in the directory `linear_solver_routines`.
- [x] Create a mutable struct for the solver.
- [x] Create a constructor with default values for your struct.
- [x] Create a function `rsubsolve!` (a template can be found in src/linear_solver_routines.jl):
        INPUTS: 
	- [x]         1.`type`, your mutable struct
	- [x]         2.`x`, an `AbstractVector` 
	- [x]         3. `samp`, a tuple whose values differ between row and column routines.
             - Row routines should have `Tuple{U,V,W} where {U<:Union{AbstractVector,AbstractMatrix},
             V<:AbstractArray,W<:AbstractVector}`.
            - Column routines should have samp::Tuple{U,V,W,X} where `{U<:Union{AbstractVector,AbstractMatrix},
             V<:AbstractArray,W<:AbstractVector,X<:AbstractVector}`
	- [x]         4. `iter` an `Int64`
        OUTPUTS:
	- [x]         1. Should update the value of `x` but not return anything.
- [x] Add an include("linear_solver_routines/[YOURFILE]") under the heading that best fits you method in src/linear_solver_routines.jl.
- [x] Add import statements to src/RLinearAlgebra.jl with any functions from other packages that you use.
- [x] Add your structure to the list of exported linear solver routines in src/RLinearAlgebra.jl.
- [x] Add your structure to docs/src/api/linear_solver_routines.md under the appropiate heading. 
- [x] Add a procedural test to test/linear_solver_routines.
2. Pull request
- [x] Give a specific title to pull request.
- [x] Lay out the features added to the pull request.
- [x] Tag two people to review your pull request.

**Comment by VChristian** [comment]
Pull request initiated:

- [ ] Get reviews 
- [ ] Update code if any changes
- [ ] Resubmit

**Comment by vp314** [comment]
@VChristian Did you close the issue in your PR?

**Comment by vp314** [comment]
Closed by #54
